version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    restart: always
  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./docker/data/mongo-data:/data/db
  discovery-server:
    container_name: eureka
    build:
      context: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - discovery-server
    restart: always

  product-service:
    container_name: product-service
    build:
      context: product-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo
      - discovery-server
      - api-gateway

  order-service:
    container_name: order-service
    build:
      context: order-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - zipkin
      - discovery-server
      - api-gateway

  inventory-service:
    container_name: inventory-service
    build:
      context: inventory-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - zipkin
      - discovery-server
      - api-gateway

  user-journey-service:
    container_name: user-journey-service
    build:
      context: user-journey-service
    restart: always
    depends_on:
      - api-gateway
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
      image: grafana/grafana-oss:8.5.2
      container_name: grafana
      restart: always
      ports:
        - "3000:3000"
      links:
        - prometheus:prometheus
      volumes:
        - ./docker/data/grafana:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
