eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway


## Define product-service, Order-Service, Discovery-server Route. https://www.youtube.com/watch?v=8PJUnnhLXiI&ab_channel=ProgrammingTechie
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/api/product
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/api/order
      - id: user-journey-service
        uri: http://localhost:8000
        predicates:
          - Path=/api/journey
      - id: discovery-server
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/
      - id: discovery-server-static-resources
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: prometheus