spring:
  application:
    name: product-service
  lifecycle:
    timeout-per-shutdown-phase: 10s

  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
  shutdown: graceful


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes.enabled: true
      group.readiness.include: mongo

