spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus