spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/inventory-service
    username: root
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
